version: 2.17
jobs:
  build:
    working_directory: ~/taskapp
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
      - run:
          name: install-npm
          command: npm ci
      - save_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
          paths:
            - ./node_modules
  deploy:
    working_directory: ~/taskapp
    machine:
      enabled: true
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{checksum "package-lock.json"}}
      - run:
          name: Zip app
          command:  |
            pwd
            ls
            zip -r taskapp.zip ./
      - run:
          name: Deploy over SSH
          command:  |
            ssh  ubuntu@44.197.114.219 "sudo rm -rf ./taskapp || true; mkdir taskapp; pm2 stop all || true; pm2 delete all || true;";
            scp taskapp.zip ubuntu@44.197.114.219:~/taskapp/taskapp.zip;
            ssh  ubuntu@44.197.114.219 "ls; cd taskapp; unzip taskapp.zip; pm2 start index.js --name taskapp;";

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold